### ISSUE TITLE
Polishing up Cafepress store

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#218]
Hey @alexklinger - as your sort of "wrap up" project I think we will have you work on our cafepress store.

Currently, the store is inactive, but the merchandise and such are soon to be reactivated (as assigned in #184).

You can see the "shell" of the store here:
http://www.cafepress.com/phetsims

It might be worth looking at some popular stores on CafePress and seeing what is done well. Unfortunately, the Cafepress system is kind of cumbersome and annoying to deal with, but we can talk about it once the merchandise is restored. Having some html knowledge will definitely be beneficial in getting things polished.

This task can also include some creative tasks once we get things organized (such as coming up with a few t-shirts and such). You and I can discuss more the week of 4/20/2014 when I am back from the conference.

**Comment by ariel-phet** [comment]
OK, @alexklinger the merchandise how now been reactivated. Please take a look when you get a chance.

**Comment by alexklinger** [comment]
@ariel-phet Hey, can you send me the log in for the cafe press, i'm curious to see what it looks like from that end.

**Comment by ariel-phet** [comment]
@alexklinger - the log in information has been sent to your colorado.edu email addy

**Comment by alexklinger** [comment]
I'm using this thread as image hosting for now, maybe we can transfer over to your preferred server later. 

![cafepressideas](https://cloud.githubusercontent.com/assets/8651105/7438819/33602052-f028-11e4-9820-ef53ec1c4c0e.jpg)

**Comment by ariel-phet** [comment]
That seems perfectly fine for the moment. Nice looking banner!

**Comment by alexklinger** [comment]
@ariel-phet I think I'm getting close to a point for feedback on the store. http://www.cafepress.com/phetsims

**Comment by amanda-phet** [comment]
The banner looks great. I like the overall look of the store. 

Something we noticed when trying to set up the store is that the "tabs" at the top don't really work, but the links on the left-hand navigation do. Our thought is that the tabs at the top should work the way the links to... clicking T-Shirts & Clothing should take you to.. the collection of T-Shirts & Clothing. Can you get that working?

Also, it would be ideal to have an indicator for which "tab" you are currently viewing. Maybe giving it a tab-like appearance, or a different color for the text. 

Thanks! Looking good!

**Comment by ariel-phet** [comment]
@zepumph please work on polishing up the cafe press store and any bugs you notice

**Comment by zepumph** [comment]
I fixed a few bugs here and there @ariel-phet, thoughts?

http://www.cafepress.com/phetsims

**Comment by ariel-phet** [comment]
@zepumph - nice improvements. I am still seeing several issues we should address:

- [ ] When you click on a item within a category the "tab" indication goes away. For instance, if you click on a specific t-shirt the tab at the top no longer indicates "t-shirts and clothing"

- [ ] The "rollover" behavior seems really odd. For instance when you roll over an item like a mug with your mouse you get that odd logo mash up. Perhaps we could do something more like what you see here http://www.cafepress.com/dd/37977261 (even just the "highlight" rectangle would be a nice way to go, without all the social media links)

- [ ] On specific item pages something is pretty messed up with the text wrapping and window sizing and such. That would be important to improve and at least look neat and clean.

**Comment by ariel-phet** [comment]
Hey @zepumph - looks like things are coming along nicely!

The text wrapping looks much better, but I still see some minor issues such as in the screenshot below.

![capture](https://cloud.githubusercontent.com/assets/4051174/8097046/7985faec-0f9b-11e5-905d-6544fac76250.PNG)

**Comment by zepumph** [comment]
I think I figured that out, the only thing left I can see is the hover
logic in choosing an item. The overlapping logos of phet and cafepress. I'm
still thinking about how I will do that, I'll keep you posted though.

On Wed, Jun 10, 2015 at 6:06 PM, Ariel Paul <notifications@github.com>
wrote:

> Hey @zepumph <https://github.com/zepumph> - looks like things are coming
> along nicely!
>
> The text wrapping looks much better, but I still see some minor issues
> such as in the screenshot below.
>
> [image: capture]
> <https://cloud.githubusercontent.com/assets/4051174/8097046/7985faec-0f9b-11e5-905d-6544fac76250.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phetsims/tasks/issues/218#issuecomment-110952014>.
>



-- 
Michael Kauzmann
PhET Interactive Simulations
michael.phet@gmail.com

**Comment by ariel-phet** [comment]
Thanks for the update, nice work so far!

**Comment by ariel-phet** [comment]
@zepumph - there are couple last things that it would be great for you to do before you head out for the summer.

1. Can we have the PhET logo on this banner be a link back to the PhET website?
2. Can we give the banner a more permanent home? Perhaps we need a github repo like phet-cafepress (or maybe put the banner somewhere in the website repo?)

It would be great if these two changes could be done ASAP, as I am going to try finishing up the initial version of the store this week!

**Comment by zepumph** [comment]
@ariel-phet Do you only want the logo to link, or the whole banner. Also here is the link to the image: https://cloud.githubusercontent.com/assets/8651105/7442365/efb48632-f0cb-11e4-8b8c-cd62dbb28a41.jpg,
 before I move it somewhere more permanent, do you want @amanda-phet to make the middle writing a bit prettier like we had talked about before? Or any other work, It probably wouldn't be too hard, I don't know though.

**Comment by zepumph** [comment]
I just added the link to the whole banner, see what you think.

**Comment by ariel-phet** [comment]
@zepumph - I think it would be better to just link the logo (but the whole banner is a decent stopgap).

Let me talk with @amanda-phet

**Comment by zepumph** [comment]
As discussed over skype, the new banner will consist of the 'on cafe press' wording on black as the header background, and then the new svg trademarked logo will be put on top of that, as a link to the website. All resources here will be put into a new repo: phetsims/phet-cafepress.

**Comment by ariel-phet** [comment]
@zepumph - where you able to get the PhET logo up...I see the black banner but not the log working yet?

**Comment by zepumph** [comment]
Yeah I'm working on it currently, the banner works great! I'm having some trouble with the svg logo, but I'll figure it out.

**Comment by zepumph** [comment]
@ariel-phet you can take a look at it now, we ended up hosting the images from the website directly, rather than github, so the images in phet-cafepress aren't necessarily tied to cafe press at all. Any changes to those images will need to be re copied into /data/web/htdocs/phet/files/cafepress-assets on figaro, just so you know.

**Comment by zepumph** [comment]
@ariel-phet I think I fixed everything you asked for, including the nested sidebar. The main problem with the site is that a lot of the javascript is slow, because it is run everything a new page is loaded, but because we don't have access to backend, I'm not sure how we would fix this.

**Comment by amanda-phet** [comment]
I think it looks really good. There's still some oddness when rolling over some items, but I don't personally think it's a big deal.

**Comment by ariel-phet** [comment]
@zepumph - thanks for all your help on this! Now just up to me to finish getting the merch up!
