### ISSUE TITLE
[rosetta/chipper] Test HTML5 sim translation

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/tasks#271]
We need testing for html5 sim translations.

1. Go to http://phet-dev.colorado.edu/translate/
2. Select Molecules and Light as a test sim. Do not test with the other sims since they are not compatible with the translation process yet.
3. Select some locale that is not French or Afar, since these have already had some testing.
4. Fill in your translation - you can use fake strings if you want. These strings will be deployed to a test branch of babel, not master. Try filling in some fields, pressing save, closing the tab and coming back. Make sure that the saved fields remain.
5. Submit your translation. It should appear on the phet-dev site here: https://phet-dev.colorado.edu/en/simulation/molecules-and-light#translations. It will take some time to appear. The delay will mostly be caused by varnish and not the actual time to build and deploy. Make a note of any issues that appear under the debug heading after you submit.
6. Make sure the translated strings appear in the translation utility after you have submitted them. (Go back to translate the same sim and locale to check).

If the translation utility stops working, let me know exactly what you did before hand. You will need to edit your profile and make yourself a trusted translator (on phet-dev) in order to use the translation utility.

**Comment by ariel-phet** [comment]
@aaronsamuel137 - it seems we should also give a few examples of the kinds of strings used in "chains" to flesh out if there are any issues with html and such. Could you put a list of a few test strings that should be used?

**Comment by aaronsamuel137** [comment]
It would be good to test multiline strings and html strings - even if they don't appear in the english strings of MAL. You can use strings of this form for a few of the strings just to see how it works:

Multiline string example:
```Give me a\nbreak.```

HTML string example:
```Turning left on <i>red</i> is a <b>bold</b> move.```

The rest of the kinds of strings already appear in MAL.

**Comment by ariel-phet** [comment]
@phet-steele - this assignment seems tailor made for you. Think you could get it done today?

**Comment by phet-steele** [comment]
I'll commence the quality assurance.

**Comment by aaronsamuel137** [comment]
@phet-steele, I have made some fixes. Please continue testing when you have a chance.

**Comment by phet-steele** [comment]
@aaronsamuel137, I managed to make the service unavailable again. The only thing I can think I did differently, since its been working all day up until now, is that I translated all the common strings at once.

**Comment by aaronsamuel137** [comment]
It might be something to do with the fact that the build server isn't running now. Not totally sure. I am going to be updating the build server over the next few days, so now that the string saving seems to be working, you can hold off on testing until then.

**Comment by ariel-phet** [comment]
@aaronsamuel137 - status of this testing? I believe @phet-steele is finished working for the summer so we will need to assign to someone else.

**Comment by aaronsamuel137** [comment]
There were no open issues that @phet-steele left, but I think this could use more testing. There are a few things left to discuss at dev meeting, and then we should hit do a few more tests. In particular, I have pushed chains for testing different kinds of strings and concentration for testing a sim that draws strings from multiple sim repos.

**Comment by aaronsamuel137** [comment]
I think this is ready for a little more testing. @ariel-phet, do you think we should code review first or do more testing first? @phet-steele did a bit of testing, so perhaps it would be better to finish the code review before doing a second round.

**Comment by ariel-phet** [comment]
@aaronsamuel137 your call...if you want to test now, that is fine, just assign to me and I will assign to one of the testers.

**Comment by aaronsamuel137** [comment]
I'd say go ahead and do some testing. I would recommend a few tests for "chains" simulation to test multiline and html strings, and a few tests in concentration to test a normal sim that draws from different sim repos. Have the tester follow the steps on the first comment above, except for step 2, where they are welcome to use chains and concentration in addition to molecules-and-light.

Testers will need to edit their profile and make themselves a trusted translator. I would recommend doing this on both the main site and phet-dev, because every once and awhile the information on phet-dev gets over-written by the information on the main site.

Assigning to @ariel-phet

**Comment by ariel-phet** [comment]
@bryo5363 - please perform the testing @aaronsamuel137 outlines above. If you have questions, do not hesitate to contact him on skype or such.

**Comment by aaronsamuel137** [comment]
Also, you'll want to test if your name appears on the translator credits page: http://phet-dev.colorado.edu/en/for-translators/translation-credit

**Comment by bryo5363** [comment]
@aaronsamuel137 I am currently trying to get access to the translations page but according to the website I am not a trusted translator

**Comment by ariel-phet** [comment]
@bryo5363 I believe you can update your profile and mark yourself as a trusted translator (since you are part of the PhET team). Let me know if that does not work.

**Comment by bryo5363** [comment]
@ariel-phet I can no longer log in to the page. There is a 503 error

**Comment by ariel-phet** [comment]
@bryo5363 - looks like phet-dev is temporarily down, I will get one of the web developers to take a look. Try back in an hour or two, should be working again soon I imagine.

**Comment by ariel-phet** [comment]
@bryo5363 - looks like phet-dev is up and working for me again.

**Comment by bryo5363** [comment]
@ariel-phet @aaronsamuel137 I am still not able to translate the page because I am not a trusted translator. I am not able to find where to verify myself as a trusted translator

**Comment by ariel-phet** [comment]
Hey @bryo5363 - ah it appears you are not set up as a PhET team member! I will email you my login credentials

**Comment by ariel-phet** [comment]
@bryo5363 also email @aaronsamuel137 the email address you use for the site and he will set you up as a PhET team member for the future.

**Comment by aaronsamuel137** [comment]
I've made you a phet team member @bryo5363.

@ariel-phet, anyone who is a team member can easily go into the admin section and add people as team members, so if I am out of town again this doesn't need to be a blocking issue. Just go to the admin section under users, and enter their email "edit another user's profile". There will be a box at the bottom to make people phet team members.

**Comment by ariel-phet** [comment]
seems like @phet-steele has taken over most of this testing in a separate issue. Closing
