### ISSUE TITLE
CCK Donation Ask Mockups

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#395]
@mariahmaephet as we discussed we want to work on this mockup.

Here is @kathy-phet 's idea
[2015_PhET_CCKAsk_InitialIdeas.pptx](https://github.com/phetsims/tasks/files/17034/2015_PhET_CCKAsk_InitialIdeas.pptx)

As we discussed, lets try having to teachers...one gesturing/pointing to the "hey educators" message, and one pointing to the donate button.

**Comment by mariahmaephet** [comment]
@ariel-phet @kathy-phet  ?

<img width="535" alt="screen shot 2015-10-26 at 3 00 03 pm" src="https://cloud.githubusercontent.com/assets/11527557/10742357/5354e2fc-7bf2-11e5-8500-df1061f298ef.png">

**Comment by ariel-phet** [comment]
Will flesh out these notes more later, got some quick feedback from @kathy-phet 

Stuff on chalkboard hard to read (size and writing style)
Student separate from classroom seemed disjointed
Hand drawn line under the word educators highlight

**Comment by KateLRN** [comment]
Hi all,

@ariel-phet asked me to suggest some alternate language for the donation ask. 

For a more positive spin: 
Are you ready for the next generation of PhET sims? Chip in $10 to help bring this sim to HTML5.
Are you ready to leave Java sims behind? Chip in $10 to bring this sim to HTML5.
Want to see this sim in HTML5? You can help us make it happen! (feeds straight into donation ask)
Want to get this sim on your tablets? Help us make it happen!

I’m not sure about the distinction between HTML and HTML5, but I think it makes sense to clarify that you’re converting sims into the newest version of HTML. Ariel gave me the impression that teachers would know the implications of HTML5 for tablets, so I’ve removed that reference in most instances to keep it short and sweet.

Some quick notes on the design:
I love the animation style!
I agree that the text is hard to read. I’d suggest using the same font as the 'play now' button for consistency. (Sidenote: Verdana and Arial are widely regarded as the most legible fonts.)
It’s not clear to me that half of the image is addressing educators and the other half is addressing students. I’d suggest grouping the different options together with bubbles, as exemplified here (with different colours and formatting). 
![untitled](https://cloud.githubusercontent.com/assets/15362420/10792203/19c07076-7d62-11e5-8cc4-52309b8bf351.jpg)
By creating a horizontal spread instead of a vertical spread you have more room to play with, ideally filling up the user’s screen without requiring any scrolling. You also eliminate any idea of hierarchy.
PhET girl should have a background. And maybe we flip her computer around so we can see her screen, and the ‘play now’ button sits in the screen? Right now they seem disconnected.

I hope these notes are helpful! Let me know if you need anything else. :)

**Comment by ariel-phet** [comment]
@mariahmaephet - to flesh out...

1. We probably want to use a more traditional font for the writing on the chalkboard. This text will need to be clear, easy to read, and likely translatable, so best to do it in a more traditional font. 
2. Perhaps increase the size of the board so the word Educators can be highlighted...Kathy was thinking of something like a "hand drawn line" underneath the word Educators, and that word in particular could be bigger and bold to really draw the eye (or if you thin there is some other way to do that nicely)
3. Maybe try a treatment as @KateLRN suggests...side by side 
4. If we put PhET girl "in the classroom" I am not sure how to cue that students should focus on that part of the scene, but Kathy thought you might be able to think of a way
5. We are standardizing our "play with sims" icon...I will get you a link version
6. Maybe if you did the side by side layout try two chalboards on the left panel, first teacher pointing to one that says EDUCATORS big and bold, and Want to see this sim in HTML5? You can help us make it happen! Then bottom one with the teacher pointing to "donate now"

Have any thoughts on the two panel direction? I do think it could make it clearer.

The "play button" is in this folder:

https://drive.google.com/drive/folders/0B5JSfRAuRHDzfkRtWnBZNWs4WG5lQ3d0eE9WSGJuY0JSZzNfb2lzbm1FSkZLQVV5SV9UX2s 

under "help-center-with-icons" for the moment, you can use any color for the icon

**Comment by KateLRN** [comment]
Regarding @ariel-phet 's 4th point: I'd suggest putting "Educators" and "Students" headers at the top of each panel, like the grey bubbles in the picture I sent. Your call, of course!

**Comment by ariel-phet** [comment]
@mariahmaephet is waiting for a new drawing tablet, probably not much work on this until after Thursday

**Comment by mariahmaephet** [comment]
@ariel-phet @KateLRN 

How does this look layout-wise? We can keep playing with the style and colors but is this what you're imagining for having them as separate panels? 

<img width="539" alt="screen shot 2015-11-06 at 8 52 47 am" src="https://cloud.githubusercontent.com/assets/11527557/11001327/f172de20-8463-11e5-8342-e7b6dd278940.png">

I just noticed the comment about making a horizontal version. I'll try it out but my only concern is that it makes the teacher scene difficult since it has to be smushed or made more vertical somehow. I'll play around with it. 

Also, Ariel, that link you sent says that file can no longer be viewed

**Comment by ariel-phet** [comment]
Hey @mariahmaephet here is the icon file link that should work now

https://drive.google.com/drive/folders/0B5JSfRAuRHDzVU1NaVduRTF3SUk 

I think the vertical layout could work as you have it but feeling like two distinct scenes. My immediate impression is that there is way to much color going on right now, so I would tone that down. We can also get Dave's impressions once we have the concept a bit more ironed out.

**Comment by mariahmaephet** [comment]
@ariel-phet Sounds good--I'll tone it down. 

I still get this message when I try and open that link
<img width="1099" alt="screen shot 2015-11-06 at 10 02 44 am" src="https://cloud.githubusercontent.com/assets/11527557/11003060/b71cc588-846d-11e5-8224-bdb758d13b3b.png">

**Comment by ariel-phet** [comment]
@mariahmaephet it is shared with the google group...so you should be able to see it. Notice the link I put in is a new one? Are you signed in with a different gmail account?

**Comment by mariahmaephet** [comment]
@ariel-phet ohhhhh. Yep. Now it works :+1:

**Comment by KateLRN** [comment]
Looks great, @mariahmaephet ! This is precisely what I had in mind with the bubbles.

@ariel-phet My only suggestions would be to remove "Educators" on the blackboard, because I don't think it's needed anymore, and to make the 'Donate Now' link more prominent. Maybe with a button?

I'll let you guys sort out the colours. I think they look quite nice, but they draw attention away from the links.

**Comment by mariahmaephet** [comment]
@ariel-phet @KateLRN is this better? 

<img width="537" alt="screen shot 2015-11-10 at 8 27 54 am" src="https://cloud.githubusercontent.com/assets/11527557/11066337/0d54e088-8785-11e5-8f22-91d6fa54bac0.png">

**Comment by ariel-phet** [comment]
Getting there....I think this would be a good one to iterate on in person a bit, are you free sometime soon @mariahmaephet?

**Comment by KateLRN** [comment]
@mariahmaephet Awesome! I think the white/grey looks a little weird on the pale blue background (and 'play now' is hard to read), but I like the colours. Maybe make the bottom box the same colour as the top, and change PhET girl's desk to the darker brown from the blackboard so it doesn't clash? @ariel-phet what do you think?

p.s. I miss the 'play now' airplane. But I understand the argument for standardization.

**Comment by kdessau-PhET** [comment]
I like this...maybe make the text more "actionable" and shorter...as in "Ready to leave Java sims behind?"

**Comment by kathy-phet** [comment]
Overall, I like how this has evolved! Going off Kathy D's suggestion the top line could just read: 

"Ready to leave Java behind?" ... this could fit on one line and allow you to make text on top line same size as text on lower lines. I would put a bit of negative space above the "Ready" so it sits away from the edge of the blackboard.

**Comment by kathy-phet** [comment]
Previous comments also mention vertical layout. My impression is this horizontal, one over the other lay out, is working pretty well.

**Comment by ariel-phet** [comment]
@mariahmaephet lets make the following tweaks:
1. Make the blackboard black for better contrast, less colors
2. Remove chalk and erasers (a really cute touch, but I think unnecessary in this case)
3. Maybe increase the size of the blackboard horizontally and a bit vertically (so we can maximize text)
4. Make "Donate Now" a button (see the front page of the phet size for the yellow donate now button)
5. One line that says "Ready to leave Java behind"?
6. Color match desk and chalkboard frame
7. Try a much more muted color for the classroom wall (the teachers are very colorful already)

Then we can tweak more in person on Thursday :)

**Comment by mariahmaephet** [comment]
@ariel-phet @kathy-phet @KateLRN    Here's the latest version from the design meeting. I've uploaded the .ai file to my drive folder

<img width="718" alt="screen shot 2015-11-12 at 2 35 56 pm" src="https://cloud.githubusercontent.com/assets/11527557/11132009/bbdc99e0-894a-11e5-99dd-c1abdbc095a7.png">

**Comment by kdessau-PhET** [comment]
Looks good...one thing. Do you think Educators should be on one line by itself? If not, I'd push up the Chip in line a little towards the top.

**Comment by mariahmaephet** [comment]
@ariel-phet @kdessau-PhET @kathy-phet @KateLRN 

minor changes to the blackboard text

<img width="717" alt="screen shot 2015-11-12 at 2 56 17 pm" src="https://cloud.githubusercontent.com/assets/11527557/11132564/cfd72d90-894d-11e5-9bf2-385a6fb82db7.png">
<img width="717" alt="screen shot 2015-11-12 at 2 57 55 pm" src="https://cloud.githubusercontent.com/assets/11527557/11132565/cfdd8b54-894d-11e5-8cc7-32d4a7483266.png">

**Comment by kdessau-PhET** [comment]
I'm OK either way. Looks good.

**Comment by pixelzoom** [comment]
Mentioning myself so that I get updates on this issue, @pixelzoom.

**Comment by pixelzoom** [comment]
Notes from a Skype discussing with @ariel-phet about the general approach to implementing this feature.

Integrating the “Ask” dialog into Java sims has a number of drawbacks:

• The “Ask” dialog needs to reflect the look of the current PhET brand. That requires a web/HTML5 look, which will be very costly to replicate in Java. The feasibility of this has yet to be determined, but is certain to be problematic and costly to revise.

• Tweaking the dialog interaction, or disabling the dialog, will require a sim publication cycle (change, test, deploy). It will be a relatively slow, costly process to respond to user feedback about this dialog, or to experiment with wording/imagery to see how donations are affected.

• The user will suffer through this dialog every time they launch the sim, and that will becoming annoying. We will have no way of recalling whether they’ve donated already, clicked “Maybe later”, or clicked the “Play” button.  

• If a Java sim becomes broken, there will be no mechanism for soliciting donations to port the sim. If the sim can’t run, the “Ask” dialog obviously can’t be displayed.

• Translation will be difficult to add later, due to the need for the web/HTML5 look.

• If the experiment proves successful, there will be no such dialog for Flash sims.  Something similar for Flash would require a duplicate development effort, specific to Flash.

• Implementing the dialog in Java requires PhET’s most expensive development resources, test resources, and relatively long iteration cycles.

A web-based approach could be used to provide a similar user experience, with much greater flexibility and reduced cost.  When the user clicks the “Play” (and “Download”?) button on a sim’s web page, the “Ask” dialog would be displayed.  After the user interacts with the “Ask” dialog, then the sim launches as it normally does.

Advantages:

• People are used to seeing popup dialogs on webpages, and are less likely to be annoyed. 

• More flexible, easier to change.  This is especially important if the experiment is a success and we need to tweak the interaction for multiple sims.  Want to experiment with different wording/imagery in the dialog to see how it affects donations? Want to enable/disable the dialog for 1 or more sims? Instead of having to republish N sims, the behavior of the “Ask” dialog can be tweaked in one place, and will change immediately.  

• Improved user experience. If we keep track of past user interactions with the dialog, then we can decide whether to show the dialog.  For example, if they clicked the “Donate” button, then that can be remembered, so that they aren’t bothered with the dialog again. Or if they click the “Play” dialog, infer that they are a student and shouldn’t see the dialog again. 

• The dialog can be enabled/disabled for specific sims without any changes to the sims themselves. No sim testing required, no chance of introducing new bugs, no need to fiddle with brittle Java development tools.

• Implementing a dialog that looks like the current PhET brand is not an issue.

• The dialog can be used for Java and Flash sims,including sims that may (in the future) no longer run. Or even for HTML5 sims if a costly refresh is needed in the future.

• If you want to solicit international donations, the dialog can be translatable via the existing website translation tools.

• Can be implemented with less expensive web-development resources.

**Comment by pixelzoom** [comment]
Implementation tracking for this feature has been taking place in https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3707.

**Comment by ariel-phet** [comment]
Artwork task can be closed, work on task now a website issue https://github.com/phetsims/website/issues/313

**Comment by pixelzoom** [comment]
Java prototype deleted from Unfuddle SVN and associated issue has been closed, see https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3707.  (History is of course retained in Unfuddle.)
