### ISSUE TITLE
Array.isArray() is preferable to instanceof Array

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#919]
Discovered in https://github.com/phetsims/axon/issues/172, according to MDN https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray `Array.isArray()` is preferable to `instanceof Array`.  I noticed we have several places in our code that use `instanceof Array`.  Even if MDN's logic doesn't apply to our case, it may still be more idiomatic to use `isArray`. I thought we should get on the same page about this.  If we have consensus about how to proceed, we could enforce it with a lint rule.

**Comment by mattpen** [comment]
It looks like this is well supported now (http://kangax.github.io/compat-table/es5/#test-Array.isArray).  I'd say we should use Array.isArray moving forward.

**Comment by pixelzoom** [comment]
Ah, gotta love JavaScript... Apparently even `instanceof` can't be relied on for all types, and you need to understand subtle "under the hood" details to implement (what should be) simple type checks.  But I digress...

The argument against `instanceof` seems to be that ["it fails when checking arrays across frames, since the Array constructor used for the instance will likely be different to the one used for the test"](https://stackoverflow.com/questions/22289727/difference-between-using-array-isarray-and-instanceof-array). (And if someone wants to explain it to me, I'm not clear on why that's not an issue for other built-in data types.)

So yeah, we should probably be using `Array.isArray`.

**Comment by jessegreenberg** [comment]
+1 for `Array.isArray`, according to [this jsPerf test](https://jsperf.com/array-isarray-vs-instanceof-vs-constructor-check) it is also faster (though probably negligible in the scheme of things).

**Comment by pixelzoom** [comment]
Searching all .js files... 
40 occurrences of `instanceof Array`
273 occurrences of `Array.isArray`

**Comment by pixelzoom** [comment]
If we're really worried about the "across frames" issue, then we also shouldn't be doing `if ( o.constructor === SomeConstructor )`.   But how else can you test for a specific type?

**Comment by pixelzoom** [comment]
From https://shamasis.net/2011/08/infinite-ways-to-detect-array-in-javascript/  
> JavaScript (ECMA script in general) is a miraculous language. It allows us to prove that coding is creativity. One reason for that is the numerous ways a single objective can be coded. For instance, checking whether a variable is an Array, can be done in four different ways. And probably more!

Miraculous?... I had a different adjective in mind.  Especially after examining these checking hacks.

It gets better:

> This is a very slick method. Every (almost every) object has a toString method that converts an object to string. And the string representation of the array constructor is consistent and is useful enough for identification. This method is just good enough to fit into our requirements; works in almost all scenarios.
```js
isArray = function(obj) {
    return Object.prototype.toString.call(obj) == "[object Array]";
}
```

Poking around in StackOverflow, etc... The above is apparently the recommended polyfill when `Array.isArray` isn't available.  I'm having trouble typing with my jaw on the keyboard.  Relying on the format of `toString` is a cardinal sin, mind-boggling that it's a recommended solution for this problem.

**Comment by jbphet** [comment]
+1 for `Array.isArray`.

**Comment by jessegreenberg** [comment]
I am also wondering about @pixelzoom question in https://github.com/phetsims/tasks/issues/919#issuecomment-369324858, are we actually worried about the cross frame issue? If so, it would probably be for PhET-iO or third party (like LoL) reasons?

**Comment by Denz1994** [comment]
+1 to use Array.isArray. In response to @pixelzoom [comment](https://github.com/phetsims/tasks/issues/919#issuecomment-369324858) is it possible to employ some form of duck typing in cases where cross frame issues are an issue? I believe there are certain limitations such as: 

> 1. it is inexact and can have false positives
> 2. the set of properties of the object to test is arbitrary, and so it's unlikely for different people to agree on one way of doing it ([reference here](http://tobyho.com/2011/01/28/checking-types-in-javascript/))

But could unique methods to `o.constructor` be used to compare to `SomeConstructor` to determine type equivalency? These methods could have an annotation in documentation to indicate their use in type comparison.

**Comment by samreid** [comment]
> If we're really worried about the "across frames" issue, then we also shouldn't be doing `if ( o.constructor === SomeConstructor )`.   But how else can you test for a specific type?  Do we really need to resort to adding a `type` field wherever type tests are needed? 

Aren't our constructor tests all within-frame?

**Comment by pixelzoom** [comment]
@samreid asked:
> Aren't our constructor tests all within-frame?

Yes.  But cross-frame issues appear to be the (only?) reason to be concerned about Array.toArray vs instanceof.   So if we're not concerned with cross-frame issues, why not do nothing and close this issue?

**Comment by jonathanolson** [comment]
> The argument against instanceof seems to be that "it fails when checking arrays across frames, since the Array constructor used for the instance will likely be different to the one used for the test". (And if someone wants to explain it to me, I'm not clear on why that's not an issue for other built-in data types.)

If we are worried about these types of checks not working cross-frame, we would also need to do checks for Vector2 or any other type like this. For instance, if you have a Vector2 object from a sim iframe (and you type check it in another frame), you would presumably need `instanceof iframe.contentWindow.phet.dot.Vector2`, since it would be different than a Vector2 defined locally.

> Yes. And cross-frame issues appear to be the (only?) reason to be concerned about Array.toArray vs instanceof. So if we're not concerned with cross-frame issues, why not do nothing and close this issue?

This may show up in phet-io code, presumably we'd want to check that?

**Comment by pixelzoom** [comment]
@jonathanolson said:
> If we are worried about these types of checks not working cross-frame, we would also need to do checks for Vector2 or any other type like this.

Does anyone know ES5 added Array.isArray, but nothing similar was added for Number, String,... ?

**Comment by jonathanolson** [comment]
> Does anyone know ES5 added Array.isArray, but nothing similar was added for Number, String,... ?

Not sure, but we should generally be using raw numbers instead of using the `Number` type.

**Comment by samreid** [comment]
> Does anyone know ES5 added Array.isArray, but nothing similar was added for Number, String,... ?

Because `typeof` is intended to be used for numbers and strings.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> Not sure, but we should generally be using raw numbers instead of using the `Number` type.

Ah right... Use of the wrapper types (Number, String,...) is now generally discouraged, flagged as such by WebStorm. (I'll resist the urge to go off on another JS rant here.)

**Comment by samreid** [comment]
We'll go with `Array.isArray`

**Comment by jbphet** [comment]
@arnabp - let's discuss this at our next meeting before you do this.

**Comment by pixelzoom** [comment]
@arnabp @jbphet It looks like Arnab is not using the PhET code style, the formatting on these changes is incorrect.  E.g. in https://github.com/phetsims/vibe/commit/18b9bdf97e5fe31e37b3bab290bac9e12b9ac8f4:

`Array.isArray(soundInfoArray)` should be `Array.isArray( soundInfoArray )`

It looks like all of the files that were touched by commits will need to be reformatted.

**Comment by pixelzoom** [comment]
In the above commits, I fixed formatting of `Array.isArray` across the entire PhET code base.  

@arnabp Before you make any more changes to PhET code, please consult with one of the PhET developers about installing the PhET code style for your IDEA.

**Comment by arnabp** [comment]
Ah I'm sorry, I have the code style installed, but I have to manually ask webstorm to reformat the code, so I'm still getting used to it. I'll make sure it doesn't happen again.

Is there a way to have it auto-reformat code that I'm unaware of or are the manual reformats standard practice?

**Comment by samreid** [comment]
In the commit dialog, you can select "Reformat Code" in the Before Commit section:

![image](https://user-images.githubusercontent.com/679486/37254443-8350d4fe-2503-11e8-8d5f-189a1d11030f.png)

**Comment by pixelzoom** [comment]
@arnabp If you use the  "Reformat Code" feature shown above, be a tad careful.  If a file isn't formatted correctly to begin with, then you can end up obscuring the significant changes due to a bunch of formatting changes.  If the file format doesn't match PhET code style to begin with, it's preferable to update the formatting as a separate commit.

**Comment by arnabp** [comment]
Thanks everyone! I've updated my IDE and I'll definitely be getting in the habit of reformatting manually to begin with.

**Comment by pixelzoom** [comment]
Thanks @arnabp, overall nice job on this issue. And no big deal about the formatting, just wanted to make sure you were on board with the PhET code style.
