### ISSUE TITLE
Test Windows 10

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#98]
Investigate installing a Windows 10 beta on a Windows testing machine. Once we have it installed, test a Java sim, Flash sim, and a few HTML5 sims including ESPB using IE.

**Comment by ariel-phet** [comment]
Apparently Windows 10 is being released globally on July 29 2015.

@oliver-phet and @arnabp I believe @jessegreenberg is going to upgrade his computer to the computer Martin was using. His current computer might work well for doing a beta test on Windows 10.

**Comment by arnabp** [comment]
I will also be upgrading to Windows 10 on my home PC at launch, so I can help with testing until we have more windows 10 machines.

**Comment by phet-steele** [comment]
I've been planning on upgrading my personal computer as well.

**Comment by ariel-phet** [comment]
@arnabp - is there a way for us to get windows 10 before launch?

**Comment by arnabp** [comment]
yes, they have an open beta I can install onto one of our computers

**Comment by oliver-phet** [comment]
@jonathanolson JB mentioned that you have a "Scenery Unit test" that he was suggesting we use to test Windows 10 and the new browser. 
@arnabp 
You'll want to look at the unit test in addition to ESPB, Molecule Shapes, Balancing Act, RPAL.
Compare visual look to other browsers (Chrome especially).

**Comment by oliver-phet** [comment]
@arnabp Can you start testing by just around at the website and noting any weird issues.

**Comment by oliver-phet** [comment]
@arnabp Can you note in this issue general performance, issues, odd behavior, etc. you've seen on Windows 10 beta?

**Comment by arnabp** [comment]
![unit test error](https://cloud.githubusercontent.com/assets/8583364/8167153/33cb61fe-1351-11e5-8a9f-d58b12059fae.PNG)

Unit test cannot complete on Windows 10's edge. It gets hung up on the "External image displayed before load, then after load (webgl)" and never goes past that. I've also included the error log on the left.

**Comment by oliver-phet** [comment]
@jonathanolson Assigning this issues to you - it looks like Win 10 Edge is hanging on the scenery unit test.

**Comment by jonathanolson** [comment]
Fixed platform detection in https://github.com/phetsims/phet-core/issues/20, now it looks good:
![edge-unit-tests](https://cloud.githubusercontent.com/assets/480878/8177390/89edbb70-13c1-11e5-87e1-ee51d74e262a.PNG)

**Comment by arnabp** [comment]
The test is still not completing for me. Is this because you have only updated the local version?

**Comment by jonathanolson** [comment]
My fix (https://github.com/phetsims/phet-core/commit/328c6e2f6df1ee3da1bdd41877d2113cfc1e4a71) was pushed before you tested. What were you using to test, phettest? I don't know if it was updated.

**Comment by arnabp** [comment]
This link: http://phettest.colorado.edu/git-dev/scenery/tests/qunit/unit-tests.html

**Comment by jonathanolson** [comment]
Looks like phettest is out of date (http://phettest.colorado.edu/git-dev/phet-core/js/platform.js is the older version). I'll look into updating this.

**Comment by jonathanolson** [comment]
pull-all.sh was deleted on phettest.colorado.edu. I restored it, and I'm updating all repos.

**Comment by jonathanolson** [comment]
There were also random common/contrib directories, I'm refreshing things so status is clean.

**Comment by ariel-phet** [comment]
@jonathanolson - there is also now a linux box that can be set up as phettest when some time allows (probably once we have the redeploy rolling).

**Comment by jonathanolson** [comment]
> there is also now a linux box that can be set up as phettest when some time allows (probably once we have the redeploy rolling).

For now, I got the clone/pull working on phettest (just by not writing anythign in PHP/shell, all in node.js): https://github.com/phetsims/tasks/issues/9#issuecomment-114620561

**Comment by jonathanolson** [comment]
Assigning to @ariel-phet for reassignment for further testing.

**Comment by jonathanolson** [comment]
Completed successfully in Edge on further tests, closing.
